/*
 *     CoinDepo Unofficial Mobile App for Android and iOS
 *     Copyright (C) 2025  Martin Leon Bouchet
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.coindepo.app.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005CAB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0075D6)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF405F8C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFABCBFE)
val onSecondaryContainerLight = Color(0xFF355581)
val tertiaryLight = Color(0xFF234777)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3D5F90)
val onTertiaryContainerLight = Color(0xFFC4D9FF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C23)
val surfaceVariantLight = Color(0xFFDCE3F2)
val onSurfaceVariantLight = Color(0xFF404753)
val outlineLight = Color(0xFF707785)
val outlineVariantLight = Color(0xFFC0C7D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3138)
val inverseOnSurfaceLight = Color(0xFFEEF0FA)
val inversePrimaryLight = Color(0xFFA5C8FF)
val surfaceDimLight = Color(0xFFD7DAE3)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FD)
val surfaceContainerLight = Color(0xFFEBEEF7)
val surfaceContainerHighLight = Color(0xFFE5E8F2)
val surfaceContainerHighestLight = Color(0xFFDFE2EC)

val primaryLightMediumContrast = Color(0xFF003669)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF006EC9)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF123761)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4F6E9C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF0D3665)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF3D5F90)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FF)
val onBackgroundLightMediumContrast = Color(0xFF181C23)
val surfaceLightMediumContrast = Color(0xFFF9F9FF)
val onSurfaceLightMediumContrast = Color(0xFF0D1118)
val surfaceVariantLightMediumContrast = Color(0xFFDCE3F2)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F3642)
val outlineLightMediumContrast = Color(0xFF4C535F)
val outlineVariantLightMediumContrast = Color(0xFF666D7B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3138)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF0FA)
val inversePrimaryLightMediumContrast = Color(0xFFA5C8FF)
val surfaceDimLightMediumContrast = Color(0xFFC3C6D0)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF1F3FD)
val surfaceContainerLightMediumContrast = Color(0xFFE5E8F2)
val surfaceContainerHighLightMediumContrast = Color(0xFFDADDE6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCED1DB)

val primaryLightHighContrast = Color(0xFF002C57)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004A8A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF022C56)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF294A75)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002C59)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF264A79)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FF)
val onBackgroundLightHighContrast = Color(0xFF181C23)
val surfaceLightHighContrast = Color(0xFFF9F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE3F2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF252C38)
val outlineVariantLightHighContrast = Color(0xFF424956)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3138)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA5C8FF)
val surfaceDimLightHighContrast = Color(0xFFB5B9C2)
val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF0FA)
val surfaceContainerLightHighContrast = Color(0xFFDFE2EC)
val surfaceContainerHighLightHighContrast = Color(0xFFD1D4DE)
val surfaceContainerHighestLightHighContrast = Color(0xFFC3C6D0)

val primaryDark = Color(0xFFA5C8FF)
val onPrimaryDark = Color(0xFF00315F)
val primaryContainerDark = Color(0xFF2792FF)
val onPrimaryContainerDark = Color(0xFF002448)
val secondaryDark = Color(0xFFA8C8FB)
val onSecondaryDark = Color(0xFF09315B)
val secondaryContainerDark = Color(0xFF264873)
val onSecondaryContainerDark = Color(0xFF97B7E8)
val tertiaryDark = Color(0xFFA7C8FF)
val onTertiaryDark = Color(0xFF02305F)
val tertiaryContainerDark = Color(0xFF3D5F90)
val onTertiaryContainerDark = Color(0xFFC4D9FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10141A)
val onBackgroundDark = Color(0xFFDFE2EC)
val surfaceDark = Color(0xFF10141A)
val onSurfaceDark = Color(0xFFDFE2EC)
val surfaceVariantDark = Color(0xFF404753)
val onSurfaceVariantDark = Color(0xFFC0C7D6)
val outlineDark = Color(0xFF8A919F)
val outlineVariantDark = Color(0xFF404753)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE2EC)
val inverseOnSurfaceDark = Color(0xFF2D3138)
val inversePrimaryDark = Color(0xFF005FAF)
val surfaceDimDark = Color(0xFF10141A)
val surfaceBrightDark = Color(0xFF353941)
val surfaceContainerLowestDark = Color(0xFF0A0E15)
val surfaceContainerLowDark = Color(0xFF181C23)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF262A31)
val surfaceContainerHighestDark = Color(0xFF31353C)

val primaryDarkMediumContrast = Color(0xFFCADDFF)
val onPrimaryDarkMediumContrast = Color(0xFF00264C)
val primaryContainerDarkMediumContrast = Color(0xFF2792FF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCADDFF)
val onSecondaryDarkMediumContrast = Color(0xFF00264C)
val secondaryContainerDarkMediumContrast = Color(0xFF7392C2)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFCBDDFF)
val onTertiaryDarkMediumContrast = Color(0xFF00264D)
val tertiaryContainerDarkMediumContrast = Color(0xFF7192C6)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF10141A)
val onBackgroundDarkMediumContrast = Color(0xFFDFE2EC)
val surfaceDarkMediumContrast = Color(0xFF10141A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF404753)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD6DCEC)
val outlineDarkMediumContrast = Color(0xFFABB2C1)
val outlineVariantDarkMediumContrast = Color(0xFF8A909F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDFE2EC)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF262A31)
val inversePrimaryDarkMediumContrast = Color(0xFF004888)
val surfaceDimDarkMediumContrast = Color(0xFF10141A)
val surfaceBrightDarkMediumContrast = Color(0xFF41454C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF04070E)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1E25)
val surfaceContainerDarkMediumContrast = Color(0xFF24282F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2F333A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3A3E45)

val primaryDarkHighContrast = Color(0xFFEAF0FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF9FC4FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000B1E)
val secondaryDarkHighContrast = Color(0xFFEAF0FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA5C4F7)
val onSecondaryContainerDarkHighContrast = Color(0xFF000B1E)
val tertiaryDarkHighContrast = Color(0xFFEAF0FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA3C4FB)
val onTertiaryContainerDarkHighContrast = Color(0xFF000B1E)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF10141A)
val onBackgroundDarkHighContrast = Color(0xFFDFE2EC)
val surfaceDarkHighContrast = Color(0xFF10141A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF404753)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEAF0FF)
val outlineVariantDarkHighContrast = Color(0xFFBCC3D2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDFE2EC)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004888)
val surfaceDimDarkHighContrast = Color(0xFF10141A)
val surfaceBrightDarkHighContrast = Color(0xFF4C5058)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2027)
val surfaceContainerDarkHighContrast = Color(0xFF2D3138)
val surfaceContainerHighDarkHighContrast = Color(0xFF383C43)
val surfaceContainerHighestDarkHighContrast = Color(0xFF43474F)